INSERT INTO Improvements (Type, Description, Civilopedia, RequiresImprovement, Water, DestroyedWhenPillaged, OutsideBorders, BuildableOnResources) VALUES ('IMPROVEMENT_NO_IMPROVEMENT', 'TXT_KEY_IMPROVEMENT_NO_IMPROVEMENT', 'TXT_KEY_CIV5_IMPROVEMENTS_NO_IMPROVEMENT_TEXT', 1, 0, 1, 1, 1), ('IMPROVEMENT_NO_IMPROVEMENT_WATER', 'TXT_KEY_IMPROVEMENT_NO_IMPROVEMENT', 'TXT_KEY_CIV5_IMPROVEMENTS_NO_IMPROVEMENT_TEXT', 1, 1, 1, 1, 1);

INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType) SELECT 'IMPROVEMENT_NO_IMPROVEMENT', Type FROM Terrains;
INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType) SELECT 'IMPROVEMENT_NO_IMPROVEMENT_WATER', Type FROM Terrains;

INSERT INTO Builds (Type, Description, Help, Time, ImprovementType, IconAtlas, IconIndex) VALUES ('BUILD_REMOVE_IMPROVEMENT', 'TXT_KEY_BUILD_REMOVE_IMPROVEMENT', 'TXT_KEY_BUILD_REMOVE_IMPROVEMENT_HELP', 200, 'IMPROVEMENT_NO_IMPROVEMENT', 'UNIT_ACTION_REMOVE_IMPROVEMENT', 0), ('BUILD_REMOVE_IMPROVEMENT_WATER', 'TXT_KEY_BUILD_REMOVE_IMPROVEMENT', 'TXT_KEY_BUILD_REMOVE_IMPROVEMENT_HELP', 0, 'IMPROVEMENT_NO_IMPROVEMENT_WATER', 'UNIT_ACTION_REMOVE_IMPROVEMENT', 0);

INSERT INTO Unit_Builds (UnitType, BuildType) VALUES ('UNIT_WORKER', 'BUILD_REMOVE_IMPROVEMENT'), ('UNIT_WORKBOAT', 'BUILD_REMOVE_IMPROVEMENT_WATER');

INSERT INTO IconTextureAtlases (Atlas, IconSize, IconsPerRow, IconsPerColumn, Filename) VALUES ('UNIT_ACTION_REMOVE_IMPROVEMENT', 45, 1, 1, 'UnitAction45_RemoveImprovement.dds'), ('UNIT_ACTION_REMOVE_IMPROVEMENT', 64, 1, 1, 'UnitAction64_RemoveImprovement.dds');