ALTER TABLE BuildFeatures ADD COLUMN Food INT NOT NULL DEFAULT 0;

ALTER TABLE Policies ADD COLUMN AllFeatureFood INT NOT NULL DEFAULT 0;

ALTER TABLE Technologies ADD COLUMN FeatureFoodModifier INT NOT NULL DEFAULT 0;